import img from "../images/card.png";
import img2 from "../images/card_1.png";
import img3 from "../images/card_3.png";

export const movies = [
  {
    id: 1,
    name: "33 слова о дизайне",
    image: img2,
    duration: 102,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 2,
    name: "Киноальманах «100 лет дизайна»",
    image: img3,
    duration: 120,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 3,
    name: "В погоне за Бенкси",
    image: img,
    duration: 113,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 4,
    name: "Баския: Взрыв реальности",
    image: img2,
    duration: 30,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 5,
    name: "33 слова о дизайне",
    image: img3,
    duration: 40,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 6,
    name: "33 слова о дизайне",
    image: img2,
    duration: 140,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 7,
    name: "33 слова о дизайне",
    image: img,
    duration: 40,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 8,
    name: "33 слова о дизайне",
    image: img2,
    duration: 102,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 9,
    name: "33 слова о дизайне",
    image: img,
    duration: 40,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 10,
    name: "33 слова о дизайне",
    image: img,
    duration: 40,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 11,
    name: "33 слова о дизайне",
    image: img,
    duration: 102,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 12,
    name: "33 слова о дизайне",
    image: img,
    duration: 102,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 13,
    name: "33 слова о дизайне",
    image: img,
    duration: 102,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 14,
    name: "33 слова о дизайне",
    image: img,
    duration: 40,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 15,
    name: "33 слова о дизайне",
    image: img,
    duration: 40,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 16,
    name: "33 слова о дизайне",
    image: img,
    duration: 40,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 17,
    name: "33 слова о дизайне",
    image: img,
    duration: 40,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 18,
    name: "33 слова о дизайне",
    image: img,
    duration: 40,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 19,
    name: "33 слова о дизайне",
    image: img,
    duration: 40,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 20,
    name: "33 слова о дизайне",
    image: img,
    duration: 102,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 21,
    name: "33 слова о дизайне",
    image: img,
    duration: 70,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 22,
    name: "33 слова о дизайне",
    image: img,
    duration: 60,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 23,
    name: "33 слова о дизайне",
    image: img,
    duration: 90,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 24,
    name: "Война искусств",
    image: img,
    duration: 140,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
];

export const saveMovies = [
  {
    id: 1,
    name: "Война искусств",
    image: img,
    duration: 245,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 2,
    name: "Война искусств",
    image: img2,
    duration: 45,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 3,
    name: "Война искусств",
    image: img3,
    duration: 45,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 4,
    name: "Война искусств",
    image: img,
    duration: 40,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 5,
    name: "Война искусств",
    image: img,
    duration: 40,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 6,
    name: "Война искусств",
    image: img,
    duration: 40,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 7,
    name: "Война искусств",
    image: img,
    duration: 40,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
  {
    id: 8,
    name: "Война искусств",
    image: img,
    duration: 40,
    movieLink: "https://www.youtube.com/watch?v=EI65nOBRaT8",
  },
];
